version: '3'

networks:
  my_network2:
    driver: bridge

volumes:
  volume_mysql:

services:
  mysql:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_PASSWORD:
      MYSQL_DB: socle
    ports:
      - "3307:3306"
    volumes:
      - volume_mysql:/var/lib/mysql/data
    networks:
      - my_network2

  spring-app:
    build:
      context: ./project-socle-back
      dockerfile: Dockerfile
    container_name: spring_application
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/socle
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    networks:
      - my_network2

